using Blockchains.Neuralium.Classes.NeuraliumChain.Dal;
using Neuralia.Blockchains.Common.Classes.Blockchains.Common.Dal;
using Neuralia.Blockchains.Common.Classes.Blockchains.Common.Providers;

namespace Blockchains.Neuralium.Classes.NeuraliumChain.Providers {

	public interface INeuraliumChainComponentProvider : IChainComponentProvider<INeuraliumCentralCoordinator, INeuraliumChainComponentProvider, INeuraliumWalletProviderProxy, INeuraliumAssemblyProvider, INeuraliumChainFactoryProvider, INeuraliumChainStateProvider, INeuraliumChainConfigurationProvider, INeuraliumChainMiningProvider, INeuraliumChainDataLoadProvider, IAccreditationCertificateProvider, INeuraliumAccountSnapshotsProviderCommon, INeuraliumChainNetworkingProvider, INeuraliumInterpretationProviderCommon> {
	}

	public class NeuraliumChainComponentProvider : ChainComponentProvider<INeuraliumCentralCoordinator, INeuraliumChainComponentProvider, INeuraliumWalletProviderProxy, INeuraliumAssemblyProvider, INeuraliumChainFactoryProvider, INeuraliumChainStateProvider, INeuraliumChainConfigurationProvider, INeuraliumChainMiningProvider, INeuraliumChainDataLoadProvider, IAccreditationCertificateProvider, INeuraliumAccountSnapshotsProviderCommon, INeuraliumChainNetworkingProvider, INeuraliumInterpretationProviderCommon>, INeuraliumChainComponentProvider {

		public NeuraliumChainComponentProvider(INeuraliumWalletProviderProxy walletProviderProxy, INeuraliumAssemblyProvider assemblyProvider, INeuraliumChainFactoryProvider chainFactoryProvider, INeuraliumChainStateProvider chainStateProvider, INeuraliumChainConfigurationProvider chainConfigurationProvider, INeuraliumChainMiningProvider chainMiningProvider, INeuraliumChainDataLoadProvider chainDataLoadProvider, INeuraliumAccreditationCertificateProvider accreditationCertificateProvider, INeuraliumAccountSnapshotsProviderCommon accountSnapshotsProvider, INeuraliumChainNetworkingProvider neuraliumChainNetworkingProvider, INeuraliumInterpretationProviderCommon neuraliumInterpretationProvider) : base(walletProviderProxy, assemblyProvider, chainFactoryProvider, chainStateProvider, chainConfigurationProvider, chainMiningProvider, chainDataLoadProvider, accreditationCertificateProvider, accountSnapshotsProvider, neuraliumChainNetworkingProvider, neuraliumInterpretationProvider) {

		}

		public override ICardUtils CardUtils => NeuraliumCardsUtils.Instance;
	}
}