using Neuralia.Blockchains.Common.Classes.Blockchains.Common.Dal.Interfaces.AccountSnapshots.Storage;

namespace Blockchains.Neuralium.Classes.NeuraliumChain.Dal.Interfaces.AccountSnapshots.Storage {

	public interface INeuraliumAccreditationCertificatesSnapshotDal : IAccreditationCertificatesSnapshotDal {
	}

	public interface INeuraliumAccreditationCertificatesSnapshotDal<ACCOUNT_SNAPSHOT_CONTEXT, ACCREDITATION_CERTIFICATE, ACCREDITATION_CERTIFICATE_ACCOUNT_SNAPSHOT> : IAccreditationCertificatesSnapshotDal<ACCOUNT_SNAPSHOT_CONTEXT, ACCREDITATION_CERTIFICATE, ACCREDITATION_CERTIFICATE_ACCOUNT_SNAPSHOT>, INeuraliumAccreditationCertificatesSnapshotDal
		where ACCOUNT_SNAPSHOT_CONTEXT : INeuraliumAccreditationCertificatesSnapshotContext<ACCREDITATION_CERTIFICATE, ACCREDITATION_CERTIFICATE_ACCOUNT_SNAPSHOT>
		where ACCREDITATION_CERTIFICATE : class, INeuraliumAccreditationCertificateSnapshotEntry<ACCREDITATION_CERTIFICATE_ACCOUNT_SNAPSHOT>
		where ACCREDITATION_CERTIFICATE_ACCOUNT_SNAPSHOT : class, INeuraliumAccreditationCertificateSnapshotAccountEntry {
	}
}